(load-theme 'zenburn t)

(setq dlukes-faces
      `((ido-subdir ((t (:foreground "royal blue"))))
        (slime-repl-inputed-output-face ((t (:foreground "cornflower blue"))))
        (sr-active-path-face ((t (:weight bold :height 1.0))))
        (sr-editing-path-face ((t (:background "firebrick" :foreground "gold" :weight bold :height 1.0))))
        (sr-highlight-path-face ((t (:background "gold" :foreground "dim gray" :weight bold :height 1.0))))
        (sr-html-face ((t (:foreground "cornflower blue"))))
        (sr-log-face ((t (:foreground "LightPink1"))))
        (sr-packaged-face ((t (:foreground "violet"))))
        (sr-passive-path-face ((t (:background "white" :foreground "dim gray" :weight bold :height 1.0))))
        (sr-tabs-active-face ((t (:inherit variable-pitch :background "gray30" :weight bold :height 0.9))))
        (sr-tabs-inactive-face ((t (:inherit variable-pitch :background "gray20" :height 0.9))))
        (sr-xml-face ((t (:foreground "cornflower blue"))))
        ,@(if (not (string-equal system-type "darwin"))
              '((term ((t (:inherit default :family "DejaVu Sans Mono"))))
                (term-bold ((t (:weight bold :family "DejaVu Sans Mono"))))
                (term-color-black ((t (:background "black" :foreground "black" :family "DejaVu Sans Mono"))))
                (term-color-blue ((t (:background "cornflower blue" :foreground "cornflower blue" :family "DejaVu Sans Mono"))))
                (term-color-cyan ((t (:background "cyan3" :foreground "cyan3" :family "DejaVu Sans Mono"))))
                (term-color-green ((t (:background "green3" :foreground "green3" :family "DejaVu Sans Mono"))))
                (term-color-magenta ((t (:background "magenta3" :foreground "magenta3" :family "DejaVu Sans Mono"))))
                (term-color-red ((t (:background "red3" :foreground "red3" :family "DejaVu Sans Mono"))))
                (term-color-white ((t (:background "white" :foreground "white" :family "DejaVu Sans Mono"))))
                (term-color-yellow ((t (:background "yellow3" :foreground "yellow3" :family "DejaVu Sans Mono"))))
                (term-underline ((t (:underline t :family "DejaVu Sans Mono")))))
            '((term-color-blue ((t (:background "cornflower blue" :foreground "cornflower blue"))))))))
;; '(default ((t (:family "Liberation Mono" :slant normal :weight regular :height 98))))
;; '(variable-pitch ((t (:family "Liberation Sans" :slant normal :weight regular :height 98)))))

(apply 'custom-theme-set-faces 'zenburn dlukes-faces)
